// AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
// Regenerate with: node scripts/fetch-icons.mjs
//
// MingCute icon set (https://icon-sets.iconify.design/mingcute/), Apache 2.0
// license — no attribution required, commercial use allowed. Bodies are
// inlined here so the app stays fully offline (it ships as a desktop .exe).

export type MingcuteIconName =
  | 'add-line'
  | 'ai-fill'
  | 'aiming-2-line'
  | 'aiming-line'
  | 'alert-line'
  | 'arrow-down-line'
  | 'arrow-left-down-line'
  | 'arrow-left-line'
  | 'arrow-left-up-line'
  | 'arrow-right-down-line'
  | 'arrow-right-line'
  | 'arrow-right-up-line'
  | 'arrow-up-line'
  | 'asterisk-line'
  | 'battery-automotive-fill'
  | 'brush-2-line'
  | 'camera-2-line'
  | 'check-circle-fill'
  | 'checkbox-line'
  | 'close-fill'
  | 'close-line'
  | 'color-filter-line'
  | 'color-picker-line'
  | 'columns-2-line'
  | 'copy-2-line'
  | 'cursor-2-fill'
  | 'cursor-3-fill'
  | 'cursor-fill'
  | 'delete-2-line'
  | 'directions-line'
  | 'dot-circle-line'
  | 'down-small-line'
  | 'download-2-line'
  | 'edit-2-line'
  | 'eraser-line'
  | 'eye-close-line'
  | 'eye-line'
  | 'face-mask-line'
  | 'flip-horizontal-line'
  | 'folder-line'
  | 'folder-open-line'
  | 'forbid-circle-line'
  | 'formula-line'
  | 'frame-line'
  | 'fullscreen-line'
  | 'group-line'
  | 'hand-fill'
  | 'hand-finger-fill'
  | 'hand-grab-fill'
  | 'hand-line'
  | 'hashtag-fill'
  | 'information-line'
  | 'layer-line'
  | 'layers-line'
  | 'layout-grid-line'
  | 'layout-line'
  | 'layout-top-open-line'
  | 'left-line'
  | 'left-small-line'
  | 'link-2-line'
  | 'lock-fill'
  | 'minus-circle-line'
  | 'more-1-line'
  | 'new-folder-line'
  | 'notebook-2-line'
  | 'palette-2-line'
  | 'palette-line'
  | 'pencil-fill'
  | 'pic-2-line'
  | 'pic-ai-line'
  | 'pin-fill'
  | 'pin-line'
  | 'play-fill'
  | 'rectangle-line'
  | 'right-line'
  | 'right-small-line'
  | 'scale-line'
  | 'scissors-line'
  | 'search-line'
  | 'shuffle-2-line'
  | 'sparkles-2-line'
  | 'stop-fill'
  | 'sun-line'
  | 'text-2-fill'
  | 'text-2-line'
  | 'text-line'
  | 'textbox-line'
  | 'tool-fill'
  | 'tool-line'
  | 'transfer-horizontal-line'
  | 'transfer-line'
  | 'transfer-vertical-line'
  | 'unlock-line'
  | 'up-small-line'
  | 'upload-2-line'
  | 'vector-group-line'
  | 'warning-line'
  | 'zoom-in-line';

export const MINGCUTE_ICONS: Record<MingcuteIconName, string> = {
  'add-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M5 12h14m-7 7V5\"/>",
  'ai-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M19 2a1 1 0 0 1 .946.677l.35 1.026l1.027.35a1 1 0 0 1 0 1.893l-1.026.35l-.35 1.027a1 1 0 0 1-1.893 0l-.35-1.026l-1.027-.35a1 1 0 0 1 0-1.893l1.026-.35l.35-1.027A1 1 0 0 1 19 2M9.107 5.448c.617-1.805 3.17-1.805 3.786 0l.806 2.36a4 4 0 0 0 2.493 2.493l2.36.806c1.805.617 1.805 3.17 0 3.786l-2.36.806a4 4 0 0 0-2.493 2.493l-.806 2.36c-.617 1.805-3.17 1.805-3.786 0l-.806-2.36a4 4 0 0 0-2.492-2.493l-2.36-.806c-1.806-.617-1.806-3.17 0-3.786l2.36-.806A4 4 0 0 0 8.3 7.81z\" clip-rule=\"evenodd\"/>",
  'aiming-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M20 12a8 8 0 0 1-8 8m8-8a8 8 0 0 0-8-8m8 8h1m-9 8a8 8 0 0 1-8-8m8 8v1m-8-9a8 8 0 0 1 8-8m-8 8H3m9-8V3m3 9a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z\"/>",
  'aiming-line': "<path fill=\"currentColor\" d=\"M12.5 12a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/><path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 3v3m0 12v3m-9-9h3m12 0h3m-1 0a8 8 0 1 1-16 0a8 8 0 0 1 16 0m-7.5 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/>",
  'alert-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 9v4m0 3h.002m-8.636 3.353h17.268a.5.5 0 0 0 .433-.75L12.433 3.648a.5.5 0 0 0-.866 0L2.933 18.603a.5.5 0 0 0 .433.75\"/>",
  'arrow-down-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 19V4M6.343 14L12 19.657L17.657 14\"/>",
  'arrow-left-down-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6.343 17.657L17.657 6.343M6 10v8h8\"/>",
  'arrow-left-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 12h15m-10 5.657L4.343 12L10 6.343\"/>",
  'arrow-left-up-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m6.343 6.343l11.314 11.314M14 6H6v8\"/>",
  'arrow-right-down-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17.657 17.657L6.343 6.343M10 18h8v-8\"/>",
  'arrow-right-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 12h15m-5 5.657L19.657 12L14 6.343\"/>",
  'arrow-right-up-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17.657 6.343L6.343 17.657M18 14V6h-8\"/>",
  'arrow-up-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 20V5m-5.657 5L12 4.343L17.657 10\"/>",
  'asterisk-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 4v16m6.928-12L5.072 16m0-8l13.856 8\"/>",
  'battery-automotive-fill': "<path fill=\"currentColor\" d=\"M17 3a1 1 0 0 1 1 1v1h1a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h1V4a1 1 0 0 1 2 0v1h9V4a1 1 0 0 1 1-1m-2 7a1 1 0 0 0-1 1v1h-1a1 1 0 1 0 0 2h1v1a1 1 0 1 0 2 0v-1h1a1 1 0 1 0 0-2h-1v-1a1 1 0 0 0-1-1m-9 2a1 1 0 1 0 0 2h3a1 1 0 1 0 0-2z\"/>",
  'brush-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"m10.586 19.071l8.485-8.485M8.262 4.071C9.07 5.094 9.84 6.602 10.47 8.029c.592 1.34 2.355 1.733 3.39.697l.616-.615a1.5 1.5 0 0 1 2.121 0l4.243 4.243a1.5 1.5 0 0 1 0 2.121l-6.364 6.364a1.5 1.5 0 0 1-2.122 0l-4.242-4.242a1.5 1.5 0 0 1 0-2.122l.615-.615c1.035-1.035.643-2.799-.697-3.39c-1.427-.63-2.935-1.4-3.959-2.207c-1.785-1.408-1.953-3.35-.555-4.748c1.397-1.397 3.34-1.23 4.747.556Z\"/>",
  'camera-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M3 7a1 1 0 0 1 1-1h2.586a1 1 0 0 0 .707-.293l1.414-1.414A1 1 0 0 1 9.414 4h5.172a1 1 0 0 1 .707.293l1.414 1.414a1 1 0 0 0 .707.293H20a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z\"/><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M16 12.5a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z\"/>",
  'check-circle-fill': "<path fill=\"currentColor\" d=\"M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12S6.477 2 12 2m4.95 6.38a1 1 0 0 0-1.415 0l-4.95 4.951l-2.121-2.121a1 1 0 1 0-1.414 1.414l2.829 2.828a1 1 0 0 0 1.414 0l5.656-5.657a1 1 0 0 0 0-1.414\"/>",
  'checkbox-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m7.757 11.917l2.829 2.828l5.657-5.657M5 20h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1\"/>",
  'close-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M4.575 4.576a1.5 1.5 0 0 1 2.122 0L12 9.88l5.303-5.303a1.5 1.5 0 0 1 2.122 2.121l-5.304 5.304l5.304 5.303a1.5 1.5 0 1 1-2.122 2.121L12 14.122l-5.303 5.303a1.5 1.5 0 1 1-2.122-2.12L9.88 12L4.575 6.697a1.5 1.5 0 0 1 0-2.12\" clip-rule=\"evenodd\"/>",
  'close-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m5.636 5.637l12.728 12.728m-12.728 0L18.364 5.637\"/>",
  'color-filter-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M12 13a5 5 0 1 1 4-2m-4 2a4.99 4.99 0 0 1 4-2m-4 2a5 5 0 1 1-4-2m8 0a5 5 0 1 1-4 8\"/>",
  'color-picker-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14.82 6.34a2 2 0 0 0-2.828 0l-.708.707a1 1 0 0 0 0 1.415l4.243 4.242a1 1 0 0 0 1.414 0l.707-.707a2 2 0 0 0 0-2.828l2.122-2.122a2 2 0 1 0-2.83-2.827z\"/><path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m11.992 9.169l2.828 2.828l-7.192 7.192a2 2 0 0 1-1.415.586h-2v-2a2 2 0 0 1 .586-1.414z\"/>",
  'columns-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 4v16m-7 0h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1Z\"/>",
  'copy-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M8 6V4a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1h-2M4 21h11a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1Z\"/>",
  'cursor-2-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M4.217 5.842c-.408-1.02.605-2.033 1.625-1.625L18.926 9.45c1.001.4 1.059 1.797.094 2.279l-3.918 1.959l4.676 4.676a1 1 0 0 1-1.414 1.414l-4.676-4.676l-1.959 3.918c-.482.965-1.878.907-2.278-.095z\" clip-rule=\"evenodd\"/>",
  'cursor-3-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M10 3a1 1 0 0 0-2 0v2a1 1 0 0 0 2 0zM5.464 4.05A1 1 0 1 0 4.05 5.464L5.464 6.88A1 1 0 1 0 6.88 5.464zm4.327 4.16c-.978-.326-1.907.603-1.582 1.58l3.533 10.598c.357 1.072 1.84 1.158 2.319.134l2.055-4.406l4.406-2.055c1.024-.478.938-1.962-.134-2.319zm4.159-4.16a1 1 0 0 1 0 1.414L12.536 6.88a1 1 0 1 1-1.415-1.415l1.415-1.414a1 1 0 0 1 1.414 0M2 9a1 1 0 0 1 1-1h2a1 1 0 1 1 0 2H3a1 1 0 0 1-1-1m4.879 3.536a1 1 0 1 0-1.415-1.415L4.05 12.536a1 1 0 1 0 1.414 1.414z\" clip-rule=\"evenodd\"/>",
  'cursor-fill': "<path fill=\"currentColor\" d=\"M6.68 3.422a1.1 1.1 0 0 1 1.828-.754l9.91 8.79c.733.65.315 1.861-.662 1.922l-3.088.19l2.283 5.456a1.5 1.5 0 0 1-.795 1.96l-1.787.76a1.5 1.5 0 0 1-1.97-.795l-2.42-5.724l-2.302 1.989c-.738.637-1.879.07-1.817-.903z\"/>",
  'delete-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m5 6l.876 13.133A2 2 0 0 0 7.87 21h8.258a2 2 0 0 0 1.995-1.867L19 6M8 6l.772-2.316A1 1 0 0 1 9.721 3h4.558a1 1 0 0 1 .949.684L16 6m-6 5v5m4-5v5M4 6h16\"/>",
  'directions-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 21h6M12 3v2m0 4v3m0 4v5m7-14l-1.707-1.707A1 1 0 0 0 16.586 5H10a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h6.586a1 1 0 0 0 .707-.293zM5 14l1.707-1.707A1 1 0 0 1 7.414 12H14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7.414a1 1 0 0 1-.707-.293z\"/>",
  'dot-circle-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 3h.01M12 21h.01M16.5 4.203l.01.005M7.5 19.792l.01.005M20.99 12H21M3.01 12H3m16.802 4.496l-.005.008M7.509 4.204l-.008.004m12.285 3.297l.008-.005m-15.58 8.995l-.008.005m12.289 3.286l.005.008M4.214 7.505L4.206 7.5\"/>",
  'down-small-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14.828 11L12 13.828L9.172 11\"/>",
  'download-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 16v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-4m8-13v12m-4.243-3.586L12 15.657l4.243-4.243\"/>",
  'edit-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m12.17 6.17l-7.88 7.881a1 1 0 0 0-.294.707v5.243H9.24a1 1 0 0 0 .707-.293l7.88-7.88M12.17 6.17l2.433-2.433a1 1 0 0 1 1.414 0L20.26 7.98a1 1 0 0 1 0 1.414l-2.433 2.433M12.17 6.17l5.657 5.657\"/>",
  'eraser-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m11.071 20l9.414-9.414a1 1 0 0 0 0-1.414l-5.657-5.657a1 1 0 0 0-1.414 0l-9.9 9.9a1 1 0 0 0 0 1.413l4.88 4.88A1 1 0 0 0 9.1 20zm0 0h8.93M9.878 7.05l7.07 7.071\"/>",
  'eye-close-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m14.33 14.693l.646 2.415m3.388-4.744l1.768 1.768m-10.462.561l-.647 2.415m-3.387-4.744l-1.768 1.768M4 9c2.36 7.965 13.64 7.965 16 0\"/>",
  'eye-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M21 12c0 2.5-4.03 7-9 7s-9-4.5-9-7s4.03-7 9-7s9 4.5 9 7Z\"/><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M11.012 10.262a3 3 0 0 0 2.725 2.725A1.997 1.997 0 0 1 10 12c0-.745.408-1.394 1.012-1.738Z\"/>",
  'face-mask-line': "<path fill=\"currentColor\" d=\"M9 10a1 1 0 1 0 0 2zm6 2a1 1 0 1 0 0-2zm-6 1a1 1 0 1 0 0 2zm6 2a1 1 0 1 0 0-2zm-3.275-9.922l-.274-.961zm6.494 9.728l-.995-.1zm.615-6.143l-.995-.1zm-1.44-2.122l.274-.962zm1.44 2.122l-.995-.1l-.615 6.144l.995.1l.995.099l.615-6.144zM5.78 14.806l.995-.1l-.615-6.143l-.995.1l-.995.1l.615 6.143zm.826-8.265l.275.961L12 6.04l-.275-.962l-.274-.961l-5.119 1.462zm5.668-1.463L12 6.04l5.118 1.462l.275-.961l.275-.962l-5.119-1.462zm3.753 12.908l-.447-.895l-3.134 1.567l.447.895l.448.894l3.133-1.567zm-4.922 1.567l.447-.895l-3.134-1.567l-.447.895l-.447.894l3.133 1.567zM3 12h1v-1H2v1zm18-1h-1v1h2v-1zM9 11v1h6v-2H9zm0 3v1h6v-2H9zm-3 1v-1a2 2 0 0 1-2-2H2a4 4 0 0 0 4 4zM5 9V8a3 3 0 0 0-3 3h2a1 1 0 0 1 1-1zm7.894 10.553l-.447-.895a1 1 0 0 1-.894 0l-.447.895l-.448.894a3 3 0 0 0 2.684 0zM11.725 5.078L12 6.04l.275-.962l.274-.961a2 2 0 0 0-1.098 0zm-5.944 9.728l-.995.1a5 5 0 0 0 2.739 3.974l.447-.894l.447-.895a3 3 0 0 1-1.643-2.384zm12.438 0l-.995-.1a3 3 0 0 1-1.643 2.386l.447.894l.447.894a5 5 0 0 0 2.74-3.974zM21 12h-1a2 2 0 0 1-2 2v2a4 4 0 0 0 4-4zm-2.166-3.337l.995.1a3 3 0 0 0-2.161-3.184l-.275.962l-.275.961a1 1 0 0 1 .72 1.061zM19 9v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3zM5.166 8.663l.995-.1a1 1 0 0 1 .72-1.06l-.274-.962l-.275-.962a3 3 0 0 0-2.16 3.183z\"/>",
  'flip-horizontal-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 12H3m2 7.858V15.1a.1.1 0 0 1 .1-.1h13.323c.112 0 .139.156.033.194L5.134 19.952A.1.1 0 0 1 5 19.858M5 4.142V8.9a.1.1 0 0 0 .1.1h13.323c.112 0 .139-.156.033-.194L5.134 4.048A.1.1 0 0 0 5 4.142\"/>",
  'folder-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M3 5a1 1 0 0 1 1-1h5.52a1 1 0 0 1 .78.375l1.4 1.75a1 1 0 0 0 .78.375H20a1 1 0 0 1 1 1V19a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z\"/>",
  'folder-open-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M18 20H4a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5.52a1 1 0 0 1 .78.375l1.4 1.75a1 1 0 0 0 .78.375H19a1 1 0 0 1 1 1V10M4.353 20h13.903a1 1 0 0 0 .958-.713l2.4-8A1 1 0 0 0 20.656 10H6.745a1 1 0 0 0-.958.713l-2.392 8A1 1 0 0 0 4.353 20Z\"/>",
  'forbid-circle-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m8.464 15.536l7.072-7.071M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z\"/>",
  'formula-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M18 5V4H6v2l7 6l-7 6v2h12v-1\"/>",
  'frame-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M20 7H4m13 13V4m3 13H4m3 3V4\"/>",
  'fullscreen-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 8V5a1 1 0 0 1 1-1h3M4 16v3a1 1 0 0 0 1 1h3M20 8V5a1 1 0 0 0-1-1h-3m4 12v3a1 1 0 0 1-1 1h-3\"/>",
  'group-line': "<path fill=\"currentColor\" d=\"M20 18a1 1 0 1 0 2 0zm-5 1a1 1 0 1 0 2 0zM2 19a1 1 0 1 0 2 0zm15-5v1h2v-2h-2zm4 2h-1v2h2v-2zm-1-7h-1a1 1 0 0 1-1 1v2a3 3 0 0 0 3-3zm-2 2v-1a1 1 0 0 1-1-1h-2a3 3 0 0 0 3 3zm-2-2h1a1 1 0 0 1 1-1V6a3 3 0 0 0-3 3zm2-2v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3zM6 14v1h7v-2H6zm10 3h-1v2h2v-2zM3 19h1v-2H2v2zM13 7.5h-1A2.5 2.5 0 0 1 9.5 10v2A4.5 4.5 0 0 0 14 7.5zM9.5 11v-1A2.5 2.5 0 0 1 7 7.5H5A4.5 4.5 0 0 0 9.5 12zM6 7.5h1A2.5 2.5 0 0 1 9.5 5V3A4.5 4.5 0 0 0 5 7.5zM9.5 4v1A2.5 2.5 0 0 1 12 7.5h2A4.5 4.5 0 0 0 9.5 3zM13 14v1a2 2 0 0 1 2 2h2a4 4 0 0 0-4-4zm-7 0v-1a4 4 0 0 0-4 4h2a2 2 0 0 1 2-2zm13 0v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3z\"/>",
  'hand-fill': "<path fill=\"currentColor\" d=\"M12 1c-1.104 0-1.8.895-1.8 2l-.2 7.998c0-.364-.375-5.06-.5-5.998c-.091-.685-.7-2-1.7-2C6.695 3 6 3.895 6 5v6.21a3 3 0 0 1-.487-.622c-.22-.348-.405-.64-1.12-.868c-.643-.204-1.276.103-1.84.385a1 1 0 0 0-.447 1.342l3.065 6.13A8 8 0 0 0 12.326 22H13a8 8 0 0 0 8-8V8c0-1.105-.562-2-1.5-2s-1.2 1-1.2 2c0 .422-.217 4.22-.3 4.268V5c0-1.105-.695-2-1.8-2s-1.7 1-1.7 2c0 .167-.12 1.53-.243 2.917C14.129 9.353 14 10.815 14 11l-.2-8c0-1.105-.695-2-1.8-2\"/>",
  'hand-finger-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M7 4.5a2.5 2.5 0 1 1 5 0v4.605l5.442.605A4 4 0 0 1 21 13.685V14a8 8 0 0 1-8 8h-.674a8 8 0 0 1-7.155-4.422l-3.065-6.13a1 1 0 0 1 .447-1.342c1.115-.558 2.194-.816 3.332-.342c.385.161.753.398 1.115.698z\" clip-rule=\"evenodd\"/>",
  'hand-grab-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M10.388 5.162a2.498 2.498 0 0 1 4.224 0a2.5 2.5 0 0 1 3.349 1.896Q18.222 7 18.5 7A2.5 2.5 0 0 1 21 9.5V12a8 8 0 0 1-8 8h-.674a8 8 0 0 1-7.155-4.422l-3.065-6.13a1 1 0 0 1 .447-1.342c1.115-.558 2.194-.816 3.332-.342c.385.161.753.398 1.115.698V7.5a2.5 2.5 0 0 1 3.388-2.338\" clip-rule=\"evenodd\"/>",
  'hand-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 11v3a7 7 0 0 1-7 7h-.674a7 7 0 0 1-6.26-3.87L3 11c2-1 3-.5 5 2V5.5a1.5 1.5 0 1 1 3 0V11V3.5a1.5 1.5 0 0 1 3 0V10V5.5a1.5 1.5 0 0 1 3 0V11V8.5a1.5 1.5 0 0 1 3 0v3.833\"/>",
  'hashtag-fill': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"3\" d=\"M5 8.5h15m-15.5 7h15M9.5 4l-2 16m9-16l-2 16\"/>",
  'information-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8h.002M11 11h1v6h.5m8.5-5a9 9 0 1 1-18 0a9 9 0 0 1 18 0\"/>",
  'layer-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 8.667L5 6v10.465a1 1 0 0 0 .445.832L11 21v-4.667M9 8.667l1.555 1.036a1 1 0 0 1 .445.832v5.798M9 8.667V4l4 2.667m-2 9.666L15 19v-4.667m-2-7.666l1.555 1.036a1 1 0 0 1 .445.832v5.798m-2-7.666V2l5.555 3.703a1 1 0 0 1 .445.832V17l-4-2.667\"/>",
  'layers-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M7 14.4v1.77a1.5 1.5 0 0 0 1.794 1.471L10 17.4m-3-3V9.64a2 2 0 0 1 1.608-1.962l6.598-1.32A1.5 1.5 0 0 1 17 7.83V9.6M7 14.4l-1.206.241A1.5 1.5 0 0 1 4 13.171V6.64a2 2 0 0 1 1.608-1.962l6.598-1.32A1.5 1.5 0 0 1 14 4.83V6.5m3 3.1l-5.392 1.078A2 2 0 0 0 10 12.64v4.76m7-7.8l1.206-.241A1.5 1.5 0 0 1 20 10.829v6.531a2 2 0 0 1-1.608 1.962l-6.598 1.32A1.5 1.5 0 0 1 10 19.17V17.4\"/>",
  'layout-grid-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M4 12h16m-8-8v16m-7 0h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1Z\"/>",
  'layout-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M4 9h16M10 9v11m-5 0h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1Z\"/>",
  'layout-top-open-line': "<path fill=\"currentColor\" d=\"M10.586 12.793a1 1 0 0 0-1.414 1.414l.707-.707zM12 15.62l-.707.707a1 1 0 0 0 1.414 0zm2.828-1.414a1 1 0 1 0-1.414-1.414l.707.707zM20 5h-1v14h2V5zm-1 15v-1H5v2h14zM4 19h1V5H3v14zM5 4v1h14V3H5zm15 5V8H4v2h16zM9.879 13.5l-.707.707l2.12 2.121l.708-.707l.707-.707l-2.121-2.121zM12 15.621l.707.707l2.121-2.12l-.707-.708l-.707-.707l-2.121 2.121zM4 5h1V3a2 2 0 0 0-2 2zm1 15v-1H3a2 2 0 0 0 2 2zm15-1h-1v2a2 2 0 0 0 2-2zm0-14h1a2 2 0 0 0-2-2v2z\"/>",
  'left-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14.657 17.657L9 12l5.657-5.657\"/>",
  'left-small-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M13 14.828L10.172 12L13 9.172\"/>",
  'link-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m10.839 17.203l2.121 2.121a4.5 4.5 0 1 0 6.364-6.364l-2.121-2.121m-9.9 2.828l-2.121-2.121a4.5 4.5 0 1 1 6.364-6.364l2.121 2.121m-3.535 2.829l4.242 4.242\"/>",
  'lock-fill': "<path fill=\"currentColor\" d=\"M12 2a6 6 0 0 1 6 6h1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V10a2 2 0 0 1 2-2h1a6 6 0 0 1 6-6m-.107 10.005A1.998 1.998 0 0 0 11 15.729V17a1 1 0 1 0 2 0v-1.27a1.997 1.997 0 0 0-.894-3.725a1 1 0 0 0-.213 0M12 4a4 4 0 0 0-4 4h8a4 4 0 0 0-4-4\"/>",
  'minus-circle-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M8 12h8m5 0a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z\"/>",
  'more-1-line': "<path fill=\"currentColor\" d=\"M12.5 12a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m6 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m-12 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M12.5 12a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm6 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm-12 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Z\"/>",
  'new-folder-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 10v6m-3-3h6M9.52 4H4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7.5a1 1 0 0 0-1-1h-7.52a1 1 0 0 1-.78-.375l-1.4-1.75A1 1 0 0 0 9.52 4\"/>",
  'notebook-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 4a1 1 0 0 1 1-1h11a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a1 1 0 0 1-1-1z\"/><path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M11 3h4v10l-2-2l-2 2z\"/>",
  'palette-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"m11 8.05l3.343-3.343a1 1 0 0 1 1.414 0l3.536 3.536a1 1 0 0 1 0 1.414L11 17.95M10 20h9a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1h-3m-5 7V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1z\"/><circle cx=\"7.5\" cy=\"15.5\" r=\".5\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"2\"/>",
  'palette-line': "<path fill=\"currentColor\" d=\"M8 12.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m2-4a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m5 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M17.902 15.484c1.322.22 2.682-.458 2.936-1.773a9 9 0 1 0-8.469 7.282c1.292-.053 1.891-1.472 1.313-2.63a2.115 2.115 0 0 1 .396-2.44l.089-.09a2.29 2.29 0 0 1 1.995-.64z\"/><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M8 12.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm2-4a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm5 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Z\"/>",
  'pencil-fill': "<path fill=\"currentColor\" d=\"M9.626 19.322a1.5 1.5 0 0 1-.723.402L4.448 20.75a1 1 0 0 1-1.2-1.2l1.027-4.455a1.5 1.5 0 0 1 .402-.723l9.09-9.091l4.95 4.95zM20.84 3.867a3 3 0 0 1 0 4.243l-.707.707l-4.95-4.95l.707-.707a3 3 0 0 1 4.243 0z\"/>",
  'pic-2-line': "<path fill=\"currentColor\" d=\"M8 8.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/><path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m21 16.1l-5.879-5.878L5.343 20M8 8.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0M4 20h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1\"/>",
  'pic-ai-line': "<path fill=\"currentColor\" d=\"M16 8.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0\"/><path fill=\"currentColor\" d=\"M4 13a1 1 0 1 0-2 0zm10.121 1.879a1 1 0 1 0 1.415 1.414l-.708-.707zm2.829-1.415l.707-.707a1 1 0 0 0-1.414 0zm3.328 4.743a1 1 0 0 0 1.414-1.414l-.707.707zm-10.4-7.571l.708-.707a1 1 0 0 0-1.415 0zm5.158 6.571a1 1 0 0 0 1.414-1.414l-.707.707zM12 3a1 1 0 1 0 0 2zM5 3l.946-.323a1 1 0 0 0-1.892 0zm3 3l.323.946a1 1 0 0 0 0-1.892zM5 9l-.946.323a1 1 0 0 0 1.892 0zM2 6l-.323-.946a1 1 0 0 0 0 1.892zm19-1h-1v14h2V5zm-1 15v-1H4v2h16zM3 19h1v-6H2v6zm11.828-3.414l.708.707l2.12-2.121l-.706-.708l-.707-.707l-2.122 2.122zm2.122-2.122l-.707.707l4.035 4.036l.707-.707l.707-.707l-4.035-4.036zm-7.071-2.828l-.707.707l5.864 5.864l.707-.707l.707-.707l-5.864-5.864zM3 17.515l.707.707l6.879-6.879l-.707-.707l-.707-.707l-6.88 6.879zM16 8.5h-1a.5.5 0 0 1 .5-.5v2A1.5 1.5 0 0 0 17 8.5zm-.5.5V8a.5.5 0 0 1 .5.5h-2a1.5 1.5 0 0 0 1.5 1.5zm-.5-.5h1a.5.5 0 0 1-.5.5V7A1.5 1.5 0 0 0 14 8.5zm.5-.5v1a.5.5 0 0 1-.5-.5h2A1.5 1.5 0 0 0 15.5 7zM12 4v1h8V3h-8zM5 3l-.946.323l.129.378l.946-.323l.946-.323l-.129-.378zm2.622 2.87l-.323.947l.378.13L8 6l.323-.946l-.378-.13zM8 6l-.323-.946l-.378.129l.323.946l.323.946l.378-.129zM5.13 8.622l-.947-.323l-.13.378L5 9l.946.323l.13-.378zM5 9l.946-.323l-.129-.378l-.946.323l-.946.323l.129.378zM2.378 6.13l.323-.947l-.378-.13L2 6l-.323.946l.378.13zM2 6l.323.946l.378-.129l-.323-.946l-.323-.946l-.378.129zm2.87-2.622l.947.323l.13-.378L5 3l-.946-.323l-.13.378zM2.379 5.871l.323.946a5 5 0 0 0 3.116-3.116l-.946-.323l-.946-.323a3 3 0 0 1-1.87 1.87zm2.493 2.75l.946-.322a5 5 0 0 0-3.116-3.116l-.323.946l-.323.946a3 3 0 0 1 1.87 1.87zM7.62 6.13l-.32-.947a5 5 0 0 0-3.116 3.116l.946.323l.946.323a3 3 0 0 1 1.87-1.87zM4 20v-1H2a2 2 0 0 0 2 2zm17-1h-1v2a2 2 0 0 0 2-2zM5.13 3.378l-.947.323a5 5 0 0 0 3.116 3.116l.323-.946l.323-.946a3 3 0 0 1-1.87-1.87zM21 5h1a2 2 0 0 0-2-2v2z\"/>",
  'pin-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M14.242 2.529a2 2 0 0 1 2.614.186l4.43 4.43a2 2 0 0 1 .186 2.614l-2.185 2.914a9 9 0 0 0-1.71 4.127l-.175 1.227a1.89 1.89 0 0 1-.969 1.413a1.78 1.78 0 0 1-1.772-.06c-1-.607-2.592-1.749-4.776-3.85l-4.249 4.25a1 1 0 0 1-1.414-1.415l4.25-4.25C6.37 11.933 5.226 10.34 4.621 9.34a1.78 1.78 0 0 1-.062-1.772a1.89 1.89 0 0 1 1.414-.97L7.2 6.425a9 9 0 0 0 4.127-1.71z\" clip-rule=\"evenodd\"/>",
  'pin-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M9.879 14.122c2.508 2.509 4.275 3.781 5.3 4.402c.534.324 1.145-.02 1.233-.638l.175-1.227a10 10 0 0 1 1.9-4.586l2.185-2.914a1 1 0 0 0-.093-1.307l-4.43-4.43a1 1 0 0 0-1.307-.093l-2.914 2.185a10 10 0 0 1-4.586 1.9l-1.227.175c-.618.088-.962.7-.639 1.233c.622 1.025 1.894 2.792 4.403 5.3Zm0 0l-4.95 4.95\"/>",
  'play-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M5.669 4.76a1.47 1.47 0 0 1 2.04-1.177c1.062.453 3.442 1.532 6.462 3.276c3.021 1.744 5.146 3.266 6.069 3.958c.788.59.79 1.763.001 2.355c-.914.687-3.013 2.191-6.07 3.956c-3.06 1.766-5.412 2.832-6.464 3.28a1.467 1.467 0 0 1-2.038-1.177c-.138-1.141-.396-3.734-.396-7.236c0-3.5.257-6.092.396-7.235\" clip-rule=\"evenodd\"/>",
  'rectangle-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" d=\"M3 6a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z\"/>",
  'right-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9.343 6.343L15 12l-5.657 5.657\"/>",
  'right-small-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M11 9.172L13.828 12L11 14.828\"/>",
  'scale-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h6m9 4V4h-4m4 0L10 14m0-4v4h4\"/>",
  'scissors-line': "<path fill=\"currentColor\" d=\"M16.984 2.283a2 2 0 0 1 .492 2.785l-4.256 6.077l1.705 2.435a4 4 0 1 1-1.415 1.465l-1.511-2.157l-1.51 2.157a4 4 0 1 1-1.415-1.465l1.704-2.436l-4.254-6.076a2 2 0 0 1 .492-2.785l4.983 7.118zM7 15.001a2 2 0 1 0 0 4a2 2 0 0 0 0-4m10 0a2 2 0 1 0 0 4a2 2 0 0 0 0-4\"/>",
  'search-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"m15.879 15.879l4.242 4.242M18 10.5a7.5 7.5 0 1 1-15 0a7.5 7.5 0 0 1 15 0Z\"/>",
  'shuffle-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M4 7h2.301a3 3 0 0 1 2.573 1.457l4.252 7.086A3 3 0 0 0 15.7 17H18M4 17h2.301a3 3 0 0 0 2.573-1.457L9.5 14.5M18 7h-2.301a3 3 0 0 0-2.573 1.457L12.5 9.5\"/><path fill=\"currentColor\" d=\"M17.579 4.654c-.28-.146-.605.065-.632.411a25 25 0 0 0-.072 1.93c0 .848.04 1.538.077 1.996c.027.324.323.503.599.36c.368-.192.905-.492 1.55-.91a20 20 0 0 0 1.476-1.056c.247-.196.258-.574.022-.762a19 19 0 0 0-1.498-1.074a19 19 0 0 0-1.523-.895m.001 10c-.28-.146-.605.065-.632.411a25 25 0 0 0-.072 1.93c0 .848.04 1.538.077 1.996c.027.324.323.503.599.36c.368-.192.905-.492 1.55-.91a20 20 0 0 0 1.476-1.056c.247-.196.258-.574.022-.762a19 19 0 0 0-1.498-1.074a19 19 0 0 0-1.523-.895\"/>",
  'sparkles-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 4h2m-1-1v2m3.5 3.212a12.7 12.7 0 0 1-4.807 5.33C8.566 13.619 8 14 8 14s.566.381.693.459a12.7 12.7 0 0 1 4.807 5.33c.075.154.5.971.5.971s.426-.817.5-.972a12.7 12.7 0 0 1 4.808-5.33C19.434 14.382 20 14 20 14s-.566-.38-.692-.459a12.7 12.7 0 0 1-4.808-5.33c-.074-.153-.5-.971-.5-.971s-.425.817-.5.972M5.815 6.859A4.7 4.7 0 0 1 4.037 8.83L3.781 9l.256.17a4.7 4.7 0 0 1 1.778 1.97c.028.058.185.36.185.36s.158-.303.185-.36a4.7 4.7 0 0 1 1.778-1.97c.047-.03.256-.17.256-.17l-.256-.17a4.7 4.7 0 0 1-1.778-1.97C6.158 6.802 6 6.5 6 6.5s-.157.302-.185.36\"/>",
  'stop-fill': "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M4 6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z\" clip-rule=\"evenodd\"/>",
  'sun-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 4V3m5.657 3.343l.707-.707M20 12h1m-3.343 5.657l.707.707M12 20v1m-5.657-3.343l-.707.707M4 12H3m3.343-5.657l-.707-.707M17 12a5 5 0 1 1-10 0a5 5 0 0 1 10 0Z\"/>",
  'text-2-fill': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\" d=\"M12 5v15m-2 0h4M5 7V5h14v2\"/>",
  'text-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 5v15m-2 0h4M5 7V5h14v2\"/>",
  'text-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 5v15M5 5h14\"/>",
  'textbox-line': "<path fill=\"currentColor\" d=\"M11 3a1 1 0 1 0 0 2zm0 16a1 1 0 1 0 0 2zm6-14a1 1 0 1 0 0-2zm0 16a1 1 0 1 0 0-2zM11 4v1h.99V3H11zm2.99 2h-1v12h2V6zm-2 14v-1H11v2h.99zM17 4V3h-1v2h1zm-3 2h-1v12h2V6zm2 14v1h1v-2h-1zm4-11h-1v6h2V9zM4 15h1V9H3v6zm1-7v1h7V7H5zm11 0v1h3V7h-3zm-4 8v-1H5v2h7zm7 0v-1h-3v2h3zM4 9h1V7a2 2 0 0 0-2 2zm0 6H3a2 2 0 0 0 2 2v-2zm16 0h-1v2a2 2 0 0 0 2-2zm0-6h1a2 2 0 0 0-2-2v2zm-4-5V3a3 3 0 0 0-3 3h2a1 1 0 0 1 1-1zm-2.01 14h-1a1 1 0 0 1-1 1v2a3 3 0 0 0 3-3zm.01 0h-1a3 3 0 0 0 3 3v-2a1 1 0 0 1-1-1zM11.99 4v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3z\"/>",
  'tool-fill': "<path fill=\"currentColor\" d=\"M4.338 6.764c-.435-.527-1.259-.466-1.497.174a7.001 7.001 0 0 0 8.299 9.227c.423-.108.882.016 1.15.36l2.966 3.825a3.648 3.648 0 1 0 5.126-5.113l-3.834-2.99c-.342-.267-.466-.724-.36-1.145a7.001 7.001 0 0 0-9.202-8.291c-.642.235-.706 1.06-.18 1.497l3.732 3.103a1 1 0 0 1 .341.965l-.282 1.416a1 1 0 0 1-.786.785l-1.411.28a1 1 0 0 1-.966-.344z\"/>",
  'tool-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M13.646 5.14a6 6 0 0 1 1.267 6.62l4.928 4.17a2.76 2.76 0 1 1-3.89 3.89l-4.17-4.927a6.002 6.002 0 0 1-7.8-8.083l3.832 4.162l2.652-.527l.53-2.655L6.83 3.96a6 6 0 0 1 6.816 1.18Z\"/>",
  'transfer-horizontal-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M11.5 8H8V5.207a.5.5 0 0 0-.854-.354L2.352 9.647a.5.5 0 0 0 0 .707l4.794 4.793A.5.5 0 0 0 8 14.793V12h8V9.205a.5.5 0 0 1 .853-.353l4.794 4.793a.5.5 0 0 1 0 .707l-4.794 4.793a.5.5 0 0 1-.854-.353V16H12.5\"/>",
  'transfer-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 9h16l-4-4m4 10H4l4 4\"/>",
  'transfer-vertical-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M16 11.5V8h2.793a.5.5 0 0 0 .353-.854l-4.793-4.793a.5.5 0 0 0-.707 0L8.853 7.146A.5.5 0 0 0 9.207 8H12v8h2.793a.5.5 0 0 1 .354.853l-4.793 4.794a.5.5 0 0 1-.707 0l-4.794-4.794A.5.5 0 0 1 5.207 16H8v-3.5\"/>",
  'unlock-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 15v2m0-2a1 1 0 1 0 0-2a1 1 0 0 0 0 2ZM7 9V8a5 5 0 0 1 7.5-4.33m3.875-.615l-.13.483m1.414 2.448l.966.26M5 21h14a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1Z\"/>",
  'up-small-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9.172 13L12 10.17L14.828 13\"/>",
  'upload-2-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 16v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-4m8-12v12M7.757 8.247L12 4.005l4.243 4.242\"/>",
  'vector-group-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6.915 19h5.17m-5.17-9H10m-5 7.085v-5.17m9 5.17V14m-2.085 0h5.17m-5.17-9h5.17M10 12.085v-5.17m9 5.17v-5.17M5.5 20a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm0-8a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm8 8a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm-3-5a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm0-8a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm8 8a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Zm0-8a1.5 1.5 0 1 1 0-3a1.5 1.5 0 0 1 0 3Z\"/>",
  'warning-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M12 7v6m0 3h.002M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z\"/>",
  'zoom-in-line': "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"2\" d=\"M7 10.5h7M10.5 14V7m5.379 8.879l4.242 4.242M18 10.5a7.5 7.5 0 1 1-15 0a7.5 7.5 0 0 1 15 0Z\"/>",
};
