"""Data backend: local SQLite."""

from typing import Any, Protocol

from .sqlite_backend import SqliteBackend


class Persistence(Protocol):
    def list_workflows(self, owner_uid: str) -> list[dict]: ...
    def create_workflow(
        self,
        owner_uid: str,
        name: str,
        icon_id: str | None = None,
        description: str | None = None,
        icon_color: str | None = None,
    ) -> dict: ...
    def get_workflow(self, owner_uid: str, wf_id: str) -> dict | None: ...
    def update_workflow(
        self,
        owner_uid: str,
        wf_id: str,
        name: str | None,
        data: dict | None,
        icon_id: str | None = None,
        description: str | None = None,
        icon_color: str | None | Any = None,
    ) -> dict | None: ...
    def delete_workflow(self, owner_uid: str, wf_id: str) -> bool: ...
    def list_collection(self, owner_uid: str, in_folder_id: str | None = None) -> list[dict]: ...
    def add_to_collection(
        self,
        owner_uid: str,
        image_bytes: bytes,
        ext: str,
        workflow_id: str | None,
        width: int | None,
        height: int | None,
    ) -> dict: ...
    def delete_collection_item(self, owner_uid: str, img_id: str) -> bool: ...
    def get_collection_bytes(self, owner_uid: str, img_id: str) -> tuple[bytes, str] | None: ...
    def get_collection_folder(self, owner_uid: str, folder_id: str) -> dict | None: ...
    def list_collection_folders(self, owner_uid: str) -> list[dict]: ...
    def create_collection_folder(self, owner_uid: str, name: str) -> dict: ...
    def rename_collection_folder(self, owner_uid: str, folder_id: str, name: str) -> dict | None: ...
    def delete_collection_folder_unlink(self, owner_uid: str, folder_id: str) -> bool: ...
    def delete_collection_folder_and_items(self, owner_uid: str, folder_id: str) -> bool: ...
    def set_collection_items_folder(
        self, owner_uid: str, img_ids: list[str], folder_id: str | None
    ) -> bool: ...
    def get_user_gemini_key(self, owner_uid: str) -> str | None: ...
    def set_user_gemini_key(self, owner_uid: str, api_key: str) -> None: ...
    def clear_user_gemini_key(self, owner_uid: str) -> None: ...
    def get_user_openai_key(self, owner_uid: str) -> str | None: ...
    def set_user_openai_key(self, owner_uid: str, api_key: str) -> None: ...
    def clear_user_openai_key(self, owner_uid: str) -> None: ...
    def get_user_fal_key(self, owner_uid: str) -> str | None: ...
    def set_user_fal_key(self, owner_uid: str, api_key: str) -> None: ...
    def clear_user_fal_key(self, owner_uid: str) -> None: ...


def get_persistence() -> Persistence:
    return SqliteBackend()
