// Regenerates src/icons/mingcuteIcons.ts and src/styles/cursors.generated.css
// from the Iconify API (https://api.iconify.design). Run with:
//   node scripts/fetch-icons.mjs
//
// The app ships fully offline (packaged as a desktop .exe), so the fetched
// icon bodies are committed as plain TS/CSS — this script only needs to run
// again when the icon list below changes.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

/** Every MingCute icon referenced anywhere in the app UI. Keep sorted-ish by
 * topic so the generated file is easy to scan and diff. */
const ICON_NAMES = [
  // Generic actions
  'close-line', 'close-fill', 'add-line', 'minus-circle-line',
  'play-fill', 'stop-fill',
  'more-1-line', 'delete-2-line', 'upload-2-line', 'download-2-line', 'copy-2-line',
  'information-line', 'layout-grid-line', 'vector-group-line', 'group-line',
  'folder-line', 'folder-open-line', 'new-folder-line', 'pic-2-line',
  'layers-line', 'layout-line', 'layout-top-open-line', 'sun-line', 'pin-fill', 'pin-line',
  'check-circle-fill', 'alert-line', 'warning-line', 'zoom-in-line', 'fullscreen-line',
  'lock-fill', 'unlock-line',
  // Directional / nudge / anchor
  'left-line', 'right-line', 'up-small-line', 'down-small-line', 'left-small-line', 'right-small-line',
  'arrow-left-up-line', 'arrow-up-line', 'arrow-right-up-line', 'arrow-left-line',
  'dot-circle-line', 'arrow-right-line', 'arrow-left-down-line', 'arrow-down-line', 'arrow-right-down-line',
  'transfer-horizontal-line', 'transfer-vertical-line',
  // Node-type icons
  'notebook-2-line', 'textbox-line', 'text-2-line', 'text-2-fill', 'directions-line', 'brush-2-line', 'camera-2-line',
  'scale-line', 'frame-line', 'eye-close-line', 'flip-horizontal-line',
  'color-filter-line', 'face-mask-line', 'color-picker-line', 'eraser-line',
  'layer-line', 'columns-2-line', 'asterisk-line', 'palette-line', 'rectangle-line', 'palette-2-line',
  'formula-line',
  'edit-2-line', 'pic-ai-line', 'sparkles-2-line', 'transfer-line', 'tool-line', 'tool-fill', 'text-line',
  'ai-fill', 'battery-automotive-fill', 'pencil-fill', 'hashtag-fill',
  'search-line', 'eye-line', 'checkbox-line', 'shuffle-2-line',
  // Cursor set
  'cursor-fill', 'cursor-2-fill', 'cursor-3-fill', 'hand-fill', 'hand-finger-fill', 'hand-line', 'hand-grab-fill',
  'link-2-line', 'aiming-line', 'aiming-2-line', 'scissors-line', 'forbid-circle-line',
];

/** Cursors baked as data-URI CSS custom properties. `hotspot` is [x, y] in
 * the icon's original 24x24 coordinate space (the script shifts it for the
 * padded viewBox automatically). */
const CURSOR_SPECS = [
  { cssVar: '--cursor-fill', icon: 'cursor-2-fill', hotspot: [3, 2] },
  { cssVar: '--cursor-2-fill', icon: 'cursor-2-fill', hotspot: [3, 2] },
  { cssVar: '--cursor-3-fill', icon: 'cursor-3-fill', hotspot: [3, 2] },
  { cssVar: '--cursor-hand-fill', icon: 'hand-fill', hotspot: [10, 8] },
  { cssVar: '--cursor-pointer', icon: 'hand-finger-fill', hotspot: [6, 1] },
  { cssVar: '--cursor-grab', icon: 'hand-line', hotspot: [12, 10] },
  { cssVar: '--cursor-grabbing', icon: 'hand-grab-fill', hotspot: [12, 12] },
  { cssVar: '--cursor-link', icon: 'link-2-line', hotspot: [12, 12] },
  { cssVar: '--cursor-aim', icon: 'aiming-line', hotspot: [12, 12] },
  { cssVar: '--cursor-aim-active', icon: 'aiming-2-line', hotspot: [12, 12] },
  { cssVar: '--cursor-scissors', icon: 'scissors-line', hotspot: [4, 4] },
  { cssVar: '--cursor-forbid', icon: 'forbid-circle-line', hotspot: [12, 12] },
  { cssVar: '--cursor-zoom-in', icon: 'zoom-in-line', hotspot: [11, 11] },
];

async function fetchIconBodies(names) {
  const unique = Array.from(new Set(names));
  const chunks = [];
  for (let i = 0; i < unique.length; i += 60) chunks.push(unique.slice(i, i + 60));

  const bodies = {};
  for (const chunk of chunks) {
    const url = `https://api.iconify.design/mingcute.json?icons=${chunk.join(',')}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Iconify request failed: ${res.status} ${url}`);
    const json = await res.json();
    for (const [name, def] of Object.entries(json.icons || {})) {
      bodies[name] = def.body;
    }
    const missing = chunk.filter((n) => !bodies[n]);
    if (missing.length) throw new Error(`Missing icon bodies for: ${missing.join(', ')}`);
  }
  return bodies;
}

function buildIconsModule(bodies) {
  const names = Object.keys(bodies).sort();
  const entries = names
    .map((name) => `  '${name}': ${JSON.stringify(bodies[name])},`)
    .join('\n');
  const unionType = names.map((n) => `  | '${n}'`).join('\n');

  return `// AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
// Regenerate with: node scripts/fetch-icons.mjs
//
// MingCute icon set (https://icon-sets.iconify.design/mingcute/), Apache 2.0
// license — no attribution required, commercial use allowed. Bodies are
// inlined here so the app stays fully offline (it ships as a desktop .exe).

export type MingcuteIconName =
${unionType};

export const MINGCUTE_ICONS: Record<MingcuteIconName, string> = {
${entries}
};
`;
}

/** A white glyph over a dilated black silhouette so the cursor reads clearly
 * on both the dark canvas and light note nodes, without a native fallback
 * image asset. */
function buildCursorSvg(body) {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="-2 -2 28 28">` +
    `<defs><filter id="o" x="-60%" y="-60%" width="220%" height="220%">` +
    `<feMorphology operator="dilate" radius="1.1"/></filter></defs>` +
    `<g filter="url(#o)" style="color:#000">${body}</g>` +
    `<g style="color:#fff">${body}</g>` +
    `</svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function buildCursorsCss(bodies) {
  const lines = CURSOR_SPECS.map(({ cssVar, icon, hotspot }) => {
    const body = bodies[icon];
    if (!body) throw new Error(`Cursor icon "${icon}" not fetched`);
    const uri = buildCursorSvg(body);
    const [hx, hy] = hotspot;
    return `  ${cssVar}: url("${uri}") ${hx + 2} ${hy + 2};`;
  });

  return `/* AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
 * Regenerate with: node scripts/fetch-icons.mjs
 *
 * Each variable is a full "url(...) hotspotX hotspotY" cursor value (no
 * trailing fallback keyword — callers append ", <native>" themselves so
 * Chromium's mandatory comma-fallback rule is satisfied at the call site).
 */
:root {
${lines.join('\n')}
}
`;
}

async function main() {
  const allNames = [...ICON_NAMES, ...CURSOR_SPECS.map((c) => c.icon)];
  const bodies = await fetchIconBodies(allNames);

  const iconsDir = resolve(ROOT, 'src/icons');
  const stylesDir = resolve(ROOT, 'src/styles');
  mkdirSync(iconsDir, { recursive: true });
  mkdirSync(stylesDir, { recursive: true });

  writeFileSync(resolve(iconsDir, 'mingcuteIcons.ts'), buildIconsModule(bodies), 'utf8');
  writeFileSync(resolve(stylesDir, 'cursors.generated.css'), buildCursorsCss(bodies), 'utf8');

  console.log(`Wrote ${Object.keys(bodies).length} icon bodies to src/icons/mingcuteIcons.ts`);
  console.log(`Wrote ${CURSOR_SPECS.length} cursor variables to src/styles/cursors.generated.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
